### PR TITLE
Updates cap script to set Drupal settings file and dir permissions.

### LINKED ISSUE #75: Drupal settings file permissions
Drupal best practices suggest that the settings file directory should be read-only (https://www.drupal.org/documentation/install/settings-file). Usually, Drupal will reset these permissions when it is able to, but a best practice is to restrict the web-servers write access to the site's executable files. Currently the Web-starter package's build scripts leave these permissions **as is** after build. This causes warnings in the site reports page to show:

> The directory sites/default is not protected from modifications and poses a security risk. You must change the directory's permissions to be non-writable. The file sites/default/settings.php is not protected from modifications and poses a security risk. You must change the file's permissions to be non-writable.

This issue is to update the Drupal build script to update settings file and directory permissions during build to comply with Drupal's best practices.

Note, the script that removes old builds already updates permissions so they are write-able before removal, so no action is necessary there.

### PR DESCRIPTION
**Pull request by johnbburg**
resolves #75

### CODE REVIEW

**Comment by wwhurley** [comment]
Can you change the hard-coded permissions to set variables? You can add something like the following to drupal.rb

```
namespace :load do
  task :defaults do
    set :settings_file_perms, '644'
    set :site_directory_perms, '750'
  end
end
```

And then a `fetch(:settings_file_perms)` and `fetch(:site_directory_perms)` instead of the numbers.

**Comment by johnbburg** [comment]
@wwhurley Does `rake load:defaults` get run somewhere? Or do I need to set that myself?

**Comment by wwhurley** [comment]
That is triggered by Capistrano.

**Comment by johnbburg** [comment]
This should now be ready to go.

**Pull request merged**
